version: '4.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env/local/dev.env
    restart: always  
    depends_on:
      - db

  
  db: 
    image: postgres:latest
    env_file:
      - .env/local/dev.env
  
     