# Generated by Django 5.0.4 on 2024-05-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='votes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TopTrack',
        ),
    ]
